# -*- coding: utf-8 -*-
"""
Created on Tue Oct 25 20:04:07 2016

@author: ERLING

This file contains the relevant classes for storing the data as a custom
structure, and the relevant methods for manipulating these structures.
"""

import numpy as np
import pandas as pd
import filehandler as fh
import datahandler as dh
import datetime
import pickle


tag_map = {'Start':'.01', 'Stop':'.02', 'OutRunning':'.03', 'Meas1':'', 'B4':'',
           'Out':'', 'ProMeas':'', 'OutMeas':'', 'OutPosition':'.01'}
sl = fh.loadDataH5('D:/Erling/NTNU/Prosjektoppgave/bigdata/data/', 'signal_list.h5') 

class Variable:
    """
    Class for storing each variable and its attributes.
    
    Attributes:
        - values: Array of values related to a timestamp.
        - timestamps: DatetimeIndex of timestamps, one for each value.
        - tagno: Tag number for the variable.
        - name: Name for the variable.
        - system: Vessel system that the variable belongs to.
        - unit: Measurement unit for the variable.
        - frequencies: Array of frequencies in Hz between each logged value.
    """
    
    def __init__(self, col):
        self.values = col.values[~np.isnan(col.values)]
        self.timestamps = col.index[~np.isnan(col.values)]
 
        (tagno, name, system, unit) = getVarNames(col)
        self.tagno = str(tagno)        
        self.name = str(name)
        self.system = str(system)
        self.unit = str(unit)
        self.frequencies = getFrequencies(self.values, self.timestamps)
    

class Data:
    """
    Class for storing a data file.
    
    Attributes:
        - variables: A dictionary mapping the variable tag number to a class
                     instance Variable containing all its information.
    """
    def __init__(self, df):
        self.variables = {col : Variable(df[col]) for col in df.columns}
        
    def save(self, filename):
        """
        save(filename) saves the data structure using pickle.
    
        Input:
        - filename: Filename, including file extension.
        """
        f = file(filename, 'wb')
        pickle.dump(self, f, pickle.HIGHEST_PROTOCOL)
        f.close()
    
    @staticmethod
    def load(filename):
        """
        load(filename) loads a data structure using pickle.
        
        Input:
            - filename: Filename, including file extension.
        """
        with file(filename, 'rb') as f:
            return pickle.load(f)
       

def name2tagno(name):
    """
    name2tagno(name) converts a variable name to a tag number.
    
    Input:
        - name: Variable name
        
    Output:
        - tagno: Variable tag number
    """
    dictionary = {'FG TO MGE2 TEMP [C]': 'GH066/Meas1/PRIM', 'SHAFT SPEED PORT  [rpm]': 'SP058/Meas1/PRIM', 'EGE 1 EXHAUST GAS OUTLET MGE2 TEMP  [C]': 'EG004/Meas1/PRIM', 'MGE4 EXHAUST GAS TEMP TC B INLET  [C]': 'MG4TE521/Meas1/PRIM', 'MAIN BEARING NO2 TEMP MGE2 [C]': 'MG2TE702/Meas1/PRIM', 'MAIN BEARING NO2 TEMP MGE3 [C]': 'MG3TE702/Meas1/PRIM', 'SW TEMP TEMP [C]': 'SW010/Meas1/PRIM', 'MG3 VOLT [V]': 'PM120.05/Meas1/PRIM', 'MAIN BEARING NO 4 TEMP MGE1 [C]': 'MG1TE704/Meas1/PRIM', 'MGE2 LO PRESS ENGINE INLET  [bar]': 'MG2PT201/Meas1/PRIM', 'VAPOUR HEADER ABS PRESS [mbar A]': 'GH020/Meas1/PRIM', 'FUEL OIL INLET PRESS MGE3  [bar]': 'MG3PT101/Meas1/PRIM', 'MG4 FREQ  [hz]': 'PM130.06/Meas1/PRIM', 'AUX CSW PUMP2 PRESS  [bar]': 'SW013/Meas1/PRIM', 'LD COMPRESSSOR2 DIS PRESS bar [bar]': 'LD156/Meas1/PRIM', 'CARGO LEVEL - TANK4  [m]': 'CT033/Meas1/PRIM', 'MG2 TC A SPEED  [rpm]': 'MG2SE518/Meas1/PRIM', 'MGE4 FUEL OIL TEMP [C]': 'OE036/Meas1/PRIM', 'MAIN BEARING NO4 TEMP MGE2 [C]': 'MG2TE704/Meas1/PRIM', 'REDUC GEAR STBD LO INLET TEMP [C]': 'RD017/Meas1/PRIM', 'AUX BOILER FUEL OIL FLOW [l/h]': 'AB161/OutMeas/PRIM', 'MAIN AIR COMPRESSSOR1 RUN [-]': 'CA005/OutRunning/PRIM', 'MGE1 AIR TEMP TC INLET  [C]': 'MG1TE600/Meas1/PRIM', 'POSITION LATITUDE [deg]': 'IBS008/Meas1/PRIM', 'MGE3 LO TEMP TC OUTLET  [C]': 'MG3TE272/Meas1/PRIM', 'SHAFT POWER PORT  [kW]': 'SP055/Meas1/PRIM', 'MGE3 HT WATER PRESS JACKET INLET  [bar]': 'MG3PT401/Meas1/PRIM', 'MGE2 LO TEMP ENGINE INLET  [C]': 'MG2TE201/Meas1/PRIM', 'MAIN AIR RESERVOIR COM LINE PRESS  [bar]': 'CA004/Meas1/PRIM', 'MAIN BEARING NO1 TEMP MGE4 [C]': 'MG4TE701/Meas1/PRIM', 'MGE1 FUEL OIL  TEMP [C]': 'OE033/Meas1/PRIM', 'MG4 POWER  [kW]': 'PM130.07/Meas1/PRIM', 'FUEL OIL INLET PRESS MGE2  [bar]': 'MG2PT101/Meas1/PRIM', 'MG1 TC A SPEED  [rpm]': 'MG1SE518/Meas1/PRIM', 'EGE 1 WATER DRUM PRESS  [bar]': 'EG011/Meas1/PRIM', 'EGE 2 EXHAUST GAS OUTLET MGE4 TEMP  [C]': 'EG006/Meas1/PRIM', 'MGE2 LO TEMP TC OUTLET  [C]': 'MG2TE272/Meas1/PRIM', 'LD COMPRESSSOR1 CURRENT (HIGH SPEED) A [A]': 'LD002.01/Meas1/PRIM', 'BOILER1 WATER CIRC PUMP1 RUN [-]': 'SM002/OutRunning/PRIM', 'MGE1 LO PRESS ENGINE INLET  [bar]': 'MG1PT201/Meas1/PRIM', 'MAIN CSW PUMP2 PRESS  [bar]': 'SW003/Meas1/PRIM', 'LD COMPRESSSOR1 DIS TEMP C [C]': 'LD054/Meas1/PRIM', 'MGE3 LO PRESS ENGINE INLET  [bar]': 'MG3PT201/Meas1/PRIM', 'N Hexane  [mol%]': 'GC_S1_COMP_nC6/Meas1/PRIM', 'GC183.03': 'GC183/OutRunning/PRIM', 'EGE 2 WATER DRUM PRESS  [bar]': 'EG012/Meas1/PRIM', 'FUEL VISCOSITY MGE3  [cst]': 'MG3512/Meas1/PRIM', 'GC143.03': 'GC143/OutRunning/PRIM', 'MAIN BEARING NO 7 TEMP MGE1 [C]': 'MG1TE707/Meas1/PRIM', 'VAPOUR HEADER PRESS H [mbar]': 'GH019/Meas1/PRIM', 'GC191.03': 'GC191/OutRunning/PRIM', 'MAIN BEARING NO7 TEMP MGE2 [C]': 'MG2TE707/Meas1/PRIM', 'BOILER FEED WATER PUMP2 RUN [-]': 'SM014/OutRunning/PRIM', 'GC151.03': 'GC151/OutRunning/PRIM', 'MAIN BEARING NO2 TEMP MGE4 [C]': 'MG4TE702/Meas1/PRIM', 'MG4_Air temp TC inlet  [C]': 'MG4TE600/Meas1/PRIM', 'BOILER2 WATER CIRC PUMP PRESS [bar]': 'SM004/Meas1/PRIM', 'CARGO TANK4 FG PUMP START [-]': 'CP033/Start/PRIM', 'DRAFT MID STBD [m]': 'RG011C/Meas1/PRIM', 'FUEL OIL LOWER CALORIFIC VALUE  [kJ/kg]': 'SP102/Meas1/PRIM', 'MAIN BEARING NO5 TEMP MGE3 [C]': 'MG3TE705/Meas1/PRIM', 'SHAFT POWER STBD  [kW]': 'SP051/Meas1/PRIM', 'CARGO TANK3 FG PUMP START [-]': 'CP032/Start/PRIM', 'BOILER1 EXHAUST GAS TEMP  [C]': 'EG001/Meas1/PRIM', 'MG3_Air temp TC inlet  [C]': 'MG3TE600/Meas1/PRIM', 'MG1 VOLT [V]': 'PM100.05/Meas1/PRIM', 'AUX CSW PUMP3 PRESS  [bar]': 'SW015/Meas1/PRIM', 'Methane From Analyser  [mol%]': 'GC_S1_COMP_C1/Meas1/PRIM', 'FUEL OIL DENSITY AT 15.6C  [kg/l]': 'SP103/Meas1/PRIM', 'FG TO MGE4 TEMP [C]': 'GH074/Meas1/PRIM', 'Nitrogen From Analyser  [mol%]': 'GC_S1_COMP_N2/Meas1/PRIM', 'CARGO LEVEL - TANK3  [m]': 'CT032/Meas1/PRIM', 'MGE1 HT WATER TEMP JACKET INLET  [C]': 'MG1TE401/Meas1/PRIM', 'FUEL OIL INLET TEMP MGE2  [C]': 'MG2TE101/Meas1/PRIM', 'MGE2 HT WATER TEMP JACKET OUTLET  [C]': 'MG2TE402/Meas1/PRIM', 'Ideal BTU  [mol%]': 'GC_S1_IdealBTU/Meas1/PRIM', 'DRAFT MID PORT [m]': 'RG010C/Meas1/PRIM', 'MGE2 HT WATER PRESS JACKET INLET  [bar]': 'MG2PT401/Meas1/PRIM', 'MGE1 EXHAUST GAS TEMP TC A INLET  [C]': 'MG1TE511/Meas1/PRIM', 'MGE2 ENGINE SPEED [rpm]': 'MG119/Meas1/PRIM', 'MG3 POWER  [kW]': 'PM120.07/Meas1/PRIM', 'CARGO TANK4 FG PUMP STOP [-]': 'CP033/Stop/PRIM', 'MG1PT901': 'MG1PT901/ProMeas/PRIM', 'STBY BALLAST PUMP CURRENT [A]': 'BL009.06/Meas1/PRIM', 'EGE 1 EXHAUST GAS OUTLET MGE1 TEMP  [C]': 'EG003/Meas1/PRIM', 'MGE1 CHARGE AIR PRESS AT ENGINE INLET  [bar]': 'MG1PT601/Meas1/PRIM', 'EGE 2 EXHAUST GAS OUTLET MGE3 TEMP  [C]': 'EG005/Meas1/PRIM', 'TRIM  [m]': 'RG020/Meas1/PRIM', 'N Butane  [mol%]': 'GC_S1_COMP_nC4/Meas1/PRIM', 'MG4 VOLT [V]': 'PM130.05/Meas1/PRIM', 'AUX COOL FW PUMP PRESS [bar]': 'LC001/Meas1/PRIM', 'BUSTIE HM1HM2 POWER  [kW]': 'PM001.05/Meas1/PRIM', 'LD COMPRESSSOR2 DIS TEMP C [C]': 'LD154/Meas1/PRIM', 'GC127.03': 'GC127/OutRunning/PRIM', 'MAIN AIR COMPRESSSOR2 RUN [-]': 'CA006/OutRunning/PRIM', 'MG2PT901': 'MG2PT901/ProMeas/PRIM', 'WIND REL DIRECTION  [deg]': 'IBS004/Meas1/PRIM', 'MGE1 FUEL OIL BOOSTER PUMP PRESS [bar]': 'OE004/Meas1/PRIM', 'MG1 CURRENT [A]': 'PM100.08/Meas1/PRIM', 'PM1 SPEED [rpm]': 'MP1090/Meas1/PRIM', 'MG2 POWER  [kW]': 'PM110.07/Meas1/PRIM', 'MGE2 HT WATER TEMP JACKET INLET  [C]': 'MG2TE401/Meas1/PRIM', 'LD COMPRESSSOR2 CURRENT (HIGH SPEED) A [A]': 'LD102.01/Meas1/PRIM', 'FEEDER HC1LC1 POWER  [kW]': 'PM031.05/Meas1/PRIM', 'STBD PROPULSION TRAFO INLET TEMP [C]': 'LC008/Meas1/PRIM', 'FG TO MGE2 FLOW [kg/h]': 'GH067.01/Meas1/PRIM', 'MG3 FREQ  [hz]': 'PM120.06/Meas1/PRIM', 'MG4 CURRENT [A]': 'PM130.08/Meas1/PRIM', 'MGE4 EXHAUST GAS TEMP TC B OUTLET  [C]': 'MG4TE527/Meas1/PRIM', 'MAIN CSW PUMP2 RUN [-]': 'SW004/OutRunning/PRIM', 'MAIN CSW PUMP3 RUN [-]': 'SW006/OutRunning/PRIM', 'PM2 Propulsion Drive FW Inlet temp [C]': 'MP2068/Meas1/PRIM', 'MAIN BEARING NO3 TEMP MGE2 [C]': 'MG2TE703/Meas1/PRIM', 'MAIN BEARING NO 0 TEMP MGE1 [C]': 'MG1TE700/Meas1/PRIM', 'CARGO TANK3 FG PUMP STOP [-]': 'CP032/Stop/PRIM', 'MGE4 HT WATER TEMP JACKET INLET  [C]': 'MG4TE401/Meas1/PRIM', 'GC135.03': 'GC135/OutRunning/PRIM', 'POSITIONLONGITUDE [min]': 'IBS011/Meas1/PRIM', 'BOILER1 WATER CIRC PUMP2 RUN [-]': 'SM003/OutRunning/PRIM', 'MG3 TC A SPEED  [rpm]': 'MG3SE518/Meas1/PRIM', 'N Pentane  [mol%]': 'GC_S1_COMP_nC5/Meas1/PRIM', 'MAIN BEARING NO5 TEMP MGE2 [C]': 'MG2TE705/Meas1/PRIM', 'FUEL OIL INLET TEMP MGE3  [C]': 'MG3TE101/Meas1/PRIM', 'MG2 CURRENT [A]': 'PM110.08/Meas1/PRIM', 'FUEL OIL HEATER OUTLET TEMP MGE2  [C]': 'MG2513/Meas1/PRIM', 'MGE2 FUEL OIL TEMP [C]': 'OE034/Meas1/PRIM', 'GCU COMBUSTION AIR  FLOW LL TRIP [mbar]': 'GC034/Meas1/PRIM', 'MG3PT901': 'MG3PT901/ProMeas/PRIM', 'B/THR MTR POWER [kW]': 'MI204/Meas1/PRIM', 'VAPOUR TO GCU PRESS [bar]': 'GH081/Meas1/PRIM', 'MGE3 EXHAUST GAS TEMP TC  OUTLET  [C]': 'MG3TE517/Meas1/PRIM', 'FUEL VISCOSITY MGE1  [cst]': 'MG1512/Meas1/PRIM', 'BALLAST PUMP2 CURRENT [A]': 'BL005.06/Meas1/PRIM', 'MGE4 LO TEMP TC OUTLET A  [C]': 'MG4TE272/Meas1/PRIM', 'REDUC GEAR PORT LO  PRESS [bar]': 'RD118/Meas1/PRIM', 'GC_S1_swi': 'GC_S1_swi/Meas1/PRIM', 'MGE2 FUEL OIL BOOSTER PUMP PRESS [bar]': 'OE007/Meas1/PRIM', 'EGE 2 EXHAUST GAS OUTLET MGE4 PRESS  [mmH2O]': 'EG010/Meas1/PRIM', 'GC_S1_COMP_iC4': 'GC_S1_COMP_iC4/Meas1/PRIM', 'FUEL OIL INLET TEMP MGE1 [C]': 'MG1TE101/Meas1/PRIM', 'AFT COOL FW OUTLET TEMP [C]': 'BH028/Meas1/PRIM', 'I Pentane  [mol%]': 'GC_S1_COMP_iC5/Meas1/PRIM', 'MGE4 HT WATER PRESS JACKET INLET  [bar]': 'MG4PT401/Meas1/PRIM', 'MGE3 LO TEMP ENGINE INLET  [C]': 'MG3TE201/Meas1/PRIM', 'MGE1 HT WATER TEMP JACKET B OUTLET  [C]': 'MG1TE403/Meas1/PRIM', 'GMS_DFEPress': 'GMS_DFEPress/Meas1/PRIM', 'FUEL OIL INLET PRESS MGE4  [bar]': 'MG4PT101/Meas1/PRIM', 'B/THR CURRENT [A]': 'MI210/Meas1/PRIM', 'MGE1 LO TEMP ENGINE INLET  [C]': 'MG1TE201/Meas1/PRIM', 'SHAFT TORQUE PORT  [kNm]': 'SP052/Meas1/PRIM', 'MAIN BEARING NO6 TEMP MGE4 [C]': 'MG4TE706/Meas1/PRIM', 'Carbon Dioxide  [mol%]': 'GC_S1_COMP_CO2/Meas1/PRIM', 'PM2 COOL FW OUTLETL TEMP  [C]': 'LC007/Meas1/PRIM', 'MGE4 CHARGE AIR TEMP AT ENGINE INLET  [C]': 'MG4TE601/Meas1/PRIM', 'Nitrogen From Manual Input  [mol%]': 'N2/Out/PRIM', 'AUX CSW PUMP1 PRESS  [bar]': 'SW011/Meas1/PRIM', 'MAIN BEARING NO4 TEMP MGE3 [C]': 'MG3TE704/Meas1/PRIM', 'SHAFT SPEED STBD  [rpm]': 'SP054/Meas1/PRIM', 'VAPOUR HEADER FWD TEMP [C]': 'GH001/Meas1/PRIM', 'BOILER1 WATER CIRC PUMP PRESS [bar]': 'SM001/Meas1/PRIM', 'MAIN CSW PUMP1 PRESS  [bar]': 'SW001/Meas1/PRIM', 'GCU EXHAUST GAS  TEMP HH TRIP [C]': 'GC033/Meas1/PRIM', 'MAIN BEARING NO0 TEMP MGE2 [C]': 'MG2TE700/Meas1/PRIM', 'VAPOUR HEADER AFT TEMP [C]': 'GH002/Meas1/PRIM', 'MAIN CENTRAL FW COOLER STBD OUTLET  TEMP  [C]': 'CF002.01/Meas1/PRIM', 'BOILER FEED WATER PUMP1 RUN [-]': 'SM012/OutRunning/PRIM', 'BUSTIE HM2HC2 POWER  [kW]': 'PM016.05/Meas1/PRIM', 'FUEL GAS FLOW TO MGE  [kg/h]': 'MGE-TOT.01/Meas1/PRIM', 'POSITION LONGITUDE [deg]': 'IBS010/Meas1/PRIM', 'MGE 2 EXHAUST GAS TEMP TC  OUTLET  [C]': 'MG2TE517/Meas1/PRIM', 'MGE3 EXHAUST GAS TEMP TC  INLET  [C]': 'MG3TE511/Meas1/PRIM', 'NITROGEN CONTENT  [mol%]': 'SP106/Meas1/PRIM', 'MGE4 TC B SPEED  [rpm]': 'MG4SE528/Meas1/PRIM', 'MGE3 ENG SPEED [rpm]': 'MG219/Meas1/PRIM', 'MAIN BEARING NO7 TEMP MGE3 [C]': 'MG3TE707/Meas1/PRIM', 'PM2 SPEED [rpm]': 'MP2090/Meas1/PRIM', 'MGE1 EXHAUST GAS TEMP TC B INLET  [C]': 'MG1TE521/Meas1/PRIM', 'MGE1 HT WATER JACKET INLET PRESS [bar]': 'MG1PT401/Meas1/PRIM', 'FUEL OIL HEATER OUTLET TEMP MGE3  [C]': 'MG3513/Meas1/PRIM', 'GCU COMBUSTION AIR  TEMP [C]': 'GC014/Meas1/PRIM', 'MGE2 HT WATER TEMP HT CAC OUTLET  [C]': 'MG2TE432/Meas1/PRIM', 'GC159.03': 'GC159/OutRunning/PRIM', 'CARGO FUEL GAS PUMP PRESS [bar]': 'CP034/Meas1/PRIM', 'MAIN BEARING NO 2 TEMP MGE1 [C]': 'MG1TE702/Meas1/PRIM', 'BOILER FEED WATER PUMP1 PRESS  [bar]': 'SM011/Meas1/PRIM', 'MDO LOWER CALORIFIC VALUE  [kJ/kg]': 'SP100/Meas1/PRIM', 'BOILER2 EXHAUST GAS TEMP  [C]': 'EG002/Meas1/PRIM', 'PORT PROPULSION TRAFO INLET TEMP [C]': 'LC009/Meas1/PRIM', 'PM1 POWER ACTUAL [kW]': 'MP1091/Meas1/PRIM', 'AUX CSW PUMP3 RUN [-]': 'SW016/OutRunning/PRIM', 'MGE3 HT WATER TEMP HT CAC OUTLET  [C]': 'MG3TE432/Meas1/PRIM', 'REDUC GEAR STBD LO  PRESS [bar]': 'RD018/Meas1/PRIM', 'GC167.03': 'GC167/OutRunning/PRIM', 'FEEDER HM2FD2 POWER  [kW]': 'PM018.05/Meas1/PRIM', 'MAIN BEARING NO0 TEMP MGE4 [C]': 'MG4TE700/Meas1/PRIM', 'MGE4 LO TEMP ENGINE INLET  [C]': 'MG4TE201/Meas1/PRIM', 'FG TO MGE1 TEMP [C]': 'GH062/Meas1/PRIM', 'FUEL OIL SULFUR CONTENT  [%]': 'SP104/Meas1/PRIM', 'EGE 1 EXHAUST GAS OUTLET MGE2 PRESS  [mmH2O]': 'EG008/Meas1/PRIM', 'MGE2 CHARGE AIR PRESSURE AT ENGINE INLET  [bar]': 'MG2PT601/Meas1/PRIM', 'MGE1 CHARGE AIR TEMP AT ENGINE INLET  [C]': 'MG1TE601/Meas1/PRIM', 'MGE4 HT WATER TEMP JACKET A OUTLET  [C]': 'MG4TE402/Meas1/PRIM', 'FUEL OIL INLET PRESS MGE1 [bar]': 'MG1PT101/Meas1/PRIM', 'SHAFT TORQUE STBD  [kNm]': 'SP056/Meas1/PRIM', 'MGE4 FUEL OIL BOOSTER PUMP PRESS [bar]': 'OE013/Meas1/PRIM', 'LIST  [deg]': 'RG021/Meas1/PRIM', 'FEEDER HM1FD1 POWER  [kW]': 'PM008.05/Meas1/PRIM', 'MGE1 LO TEMP TC OUTLET A  [C]': 'MG1TE272/Meas1/PRIM', 'LD COMPRESSSOR1 DIS PRESS bar [bar]': 'LD056/Meas1/PRIM', 'Methane From Manual Input  [mol%]': 'CH4/Out/PRIM', 'WIND SPEED  [kts]': 'IBS003/Meas1/PRIM', 'GAS LOWER CALORIFIC VALUE  [kJ/kg]': 'SP105/Meas1/PRIM', 'ATMOSPHERIC PRESS [mbar A]': 'GH026.01/Meas1/PRIM', 'FEEDER HM2LM2 POWER  [kW]': 'PM019.05/Meas1/PRIM', 'Normal Density  [mol%]': 'GC_S1_DenNor/Meas1/PRIM', 'PM2 POWER ACTUAL [kW]': 'MP2091/Meas1/PRIM', 'MIST SEPARATOR OUTLET TEMP [C]': 'FV026.01/Meas1/PRIM', '7K STEAM SERV MAIN LINE PRESS [bar]': 'SM007/Meas1/PRIM', 'AUX COOL FW PUMP2 RUN [-]': 'LC003/OutRunning/PRIM', 'MGE 2 EXHAUST GAS TEMP TC  INLET  [C]': 'MG2TE511/Meas1/PRIM', 'MAIN BEARING NO5 TEMP MGE4 [C]': 'MG4TE705/Meas1/PRIM', 'MAIN BEARING NO3 TEMP MGE4 [C]': 'MG4TE703/Meas1/PRIM', 'HEADING  [deg]': 'IBS007/Meas1/PRIM', 'MAIN BEARING NO6 TEMP MGE3 [C]': 'MG3TE706/Meas1/PRIM', 'MGE3 CHARGE AIR TEMP AT ENGINE INLET  [C]': 'MG3TE601/Meas1/PRIM', 'AUX CSW PUMP2 RUN [-]': 'SW014/OutRunning/PRIM', 'MG1 POWER  [kW]': 'PM100.07/Meas1/PRIM', 'BALLAST PUMP1 CURRENT [A]': 'BL001.06/Meas1/PRIM', 'Ethane From Manual Input  [mol%]': 'C2H6/Out/PRIM', 'BOILER FEED WATER PUMP2 PRESS  [bar]': 'SM013/Meas1/PRIM', 'MAIN BEARING NO3 TEMP MGE3 [C]': 'MG3TE703/Meas1/PRIM', 'MGE1 LO TEMP TC OUTLET B  [C]': 'MG1TE282/Meas1/PRIM', 'PM1 Propulsion Drive FW Inlet temp [C]': 'MP1068/Meas1/PRIM', 'EGE 1 EXHAUST GAS OUTLET MGE1 PRESS  [mmH2O]': 'EG007/Meas1/PRIM', 'MGE4 TC A SPEED  [rpm]': 'MG4SE518/Meas1/PRIM', 'MGE1 EXHAUST GAS TEMP TC B OUTLET  [C]': 'MG1TE527/Meas1/PRIM', 'NeoPentane  [mol%]': 'GC_S1_NeoPen/Meas1/PRIM', 'MGE3 HT WATER TEMP JACKET OUTLET  [C]': 'MG3TE402/Meas1/PRIM', 'MG2 VOLT [V]': 'PM110.05/Meas1/PRIM', 'FEEDER HC2LC2 POWER  [kW]': 'PM038.05/Meas1/PRIM', 'EGE 2 EXHAUST GAS OUTLET MGE3 PRESS  [mmH2O]': 'EG009/Meas1/PRIM', 'MGE3 CHARGE AIR PRESS AT ENGINE INLET  [bar]': 'MG3PT601/Meas1/PRIM', 'FG TO MGE1 FLOW [kg/h]': 'GH063.01/Meas1/PRIM', 'BUSTIE HC1HC2 POWER  [kW]': 'PM029.05/Meas1/PRIM', 'FUEL VISCOSITY MGE4  [cst]': 'MG4512/Meas1/PRIM', 'RUDDER ANGLE STBD [deg]': 'IBS016/Meas1/PRIM', 'FUEL VISCOSITY MGE2  [cst]': 'MG2512/Meas1/PRIM', 'Inferior Wobbe Index  [mol%]': 'GC_S1_InfWobb/Meas1/PRIM', 'MG1 TC B SPEED  [rpm]': 'MG1SE528/Meas1/PRIM', 'GCU DILUTION AIR  FLOW LOW [mbar]': 'GC016/Meas1/PRIM', 'MG3 CURRENT [A]': 'PM120.08/Meas1/PRIM', 'GAS LHV Lower Heating Value  [MJ/kg]': 'Gas_LHV/B4/PRIM', 'MAIN BEARING NO1 TEMP MGE3 [C]': 'MG3TE701/Meas1/PRIM', 'MAIN BEARING NO4 TEMP MGE4 [C]': 'MG4TE704/Meas1/PRIM', 'PM1 COOL FW OUTLETL TEMP  [C]': 'LC006/Meas1/PRIM', 'MGE4 HT WATER TEMP HT CAC OUTLET  [C]': 'MG4TE432/Meas1/PRIM', 'CARGO LEVEL - TANK2  [m]': 'CT031/Meas1/PRIM', 'Propane From Manual Input  [mol%]': 'C3H8/Out/PRIM', 'GCU OIL BURNER SECONDARY AIR FAN PRESS [mbar]': 'GC030/Meas1/PRIM', 'MG1 FREQ  [hz]': 'PM100.06/Meas1/PRIM', 'MAIN BEARING NO 5 TEMP MGE1 [C]': 'MG1TE705/Meas1/PRIM', 'MAIN BEARING NO 6 TEMP MGE1 [C]': 'MG1TE706/Meas1/PRIM', 'Unnormalised Sum  [mol%]': 'GC_S1_SUM/Meas1/PRIM', 'MAIN BEARING NO6 TEMP MGE2 [C]': 'MG2TE706/Meas1/PRIM', 'MGE4 LO PRESS ENGINE INLET  [bar]': 'MG4PT201/Meas1/PRIM', 'MGE4 MAIN FUEL GAS PRESS [bar]': 'MG4PT901/ProMeas/PRIM', 'FG TO MGE3 FLOW [kg/h]': 'GH071.01/Meas1/PRIM', 'GCU COMBUSTION AIR FLOW  [kg/h]': 'GC013/Meas1/PRIM', 'COMPRESSSORressibility Factor  [mol%]': 'GC_S1_COMPR/Meas1/PRIM', 'SPEED THROUGH WATER  [kts]': 'IBS002/Meas1/PRIM', 'DRAIN POT LVL [mm]': 'FV022/Meas1/PRIM', 'SHAFT THRUST PORT  [kN]': 'SP057/Meas1/PRIM', 'Propane From Analyser  [mol%]': 'GC_S1_COMP_C3/Meas1/PRIM', 'BOILER2 WATER CIRC PUMP2 RUN [-]': 'SM006/OutRunning/PRIM', 'GC175.03': 'GC175/OutRunning/PRIM', 'GCU EXHAUST GAS  TEMP [C]': 'GC032/Meas1/PRIM', 'VAPOUR TO GCU FLOW [kg/h]': 'GH030.01/Meas1/PRIM', 'GC_S1_shv': 'GC_S1_shv/Meas1/PRIM', 'MGE JACKET COOLING FW STBD   TEMP  [C]': 'CF003.01/Meas1/PRIM', 'MGE4 HT WATER TEMP JACKET B OUTLET  [C]': 'MG4TE403/Meas1/PRIM', 'MGE3 HT WATER TEMP JACKET INLET  [C]': 'MG3TE401/Meas1/PRIM', 'FUEL OIL HEATER OUTLET TEMP MGE1 [C]': 'MG1513/Meas1/PRIM', 'MGE4 EXHAUST GAS TEMP TC A OUTLET  [C]': 'MG4TE517/Meas1/PRIM', 'MG2_Air temp TC inlet  [C]': 'MG2TE600/Meas1/PRIM', 'DRAFT AFT [m]': 'RG012C/Meas1/PRIM', 'MGE1 ENGINE SPEED [rpm]': 'MG019/Meas1/PRIM', 'MGE1 EXHAUST GAS TEMP TC A OUTLET  [C]': 'MG1TE517/Meas1/PRIM', 'FUEL OIL HEATER OUTLET TEMP MGE4  [C]': 'MG4513/Meas1/PRIM', 'MAIN BEARING NO7 TEMP MGE4 [C]': 'MG4TE707/Meas1/PRIM', 'FG TO MGE3 TEMP [C]': 'GH070/Meas1/PRIM', 'MAIN BEARING NO 1 TEMP MGE1 [C]': 'MG1TE701/Meas1/PRIM', 'MGE4 LO TEMP TC OUTLET B  [C]': 'MG4TE282/Meas1/PRIM', 'BUSTIE HM1HC1 POWER  [kW]': 'PM002.05/Meas1/PRIM', 'SW032..03': 'SW032./OutRunning/PRIM', 'FG TO MGE4 FLOW [kg/h]': 'GH075.01/Meas1/PRIM', 'SPEED OVER GROUND  [kts]': 'IBS001/Meas1/PRIM', 'GPM  [mol%]': 'GC_S1_GPM/Meas1/PRIM', 'Water depth  [m]': 'IBS005/Meas1/PRIM', 'SW031..03': 'SW031./OutRunning/PRIM', 'REDUC GEAR PORT LO INLET TEMP [C]': 'RD117/Meas1/PRIM', 'MAIN BEARING NO1 TEMP MGE2 [C]': 'MG2TE701/Meas1/PRIM', 'MG2_CWPreheat.03': 'MG2_CWPreheat/OutRunning/PRIM', 'MAIN CSW PUMP3 PRESS  [bar]': 'SW005/Meas1/PRIM', 'AUX CSW PUMP1 RUN [-]': 'SW012/OutRunning/PRIM', 'MGE4 CHARGE AIR PRESS AT ENGINE INLET  [bar]': 'MG4PT601/Meas1/PRIM', 'MAIN CENTRAL FW COOLER PORT OUTLET  TEMP  [C]': 'CF102.01/Meas1/PRIM', 'RUDDER ANGLE PORT [deg]': 'IBS006/Meas1/PRIM', 'Ethane From Analyser  [mol%]': 'GC_S1_COMP_C2/Meas1/PRIM', 'CARGO LEVEL - TANK1  [m]': 'CT030/Meas1/PRIM', 'FUEL FLOW MGE4  [l/h]': 'MG4514/Meas1/PRIM', 'FUEL OIL MGE1 FLOW [l/h]': 'MG1514/Meas1/PRIM', 'ATMOSPHERIC TEMP [C]': 'GH026.02/Meas1/PRIM', 'MGE1 HT WATER TEMP HT CAC OUTLET  [C]': 'MG1TE432/Meas1/PRIM', 'MGE2 CHARGE AIR TEMP AT ENGINE INLET  [C]': 'MG2TE601/Meas1/PRIM', 'FEEDER HM1LM1 POWER  [kW]': 'PM005.05/Meas1/PRIM', 'MGE4 ENG SPEED [rpm]': 'MG319/Meas1/PRIM', 'MDO DENSITY AT 15.6C  [kg/l]': 'SP101/Meas1/PRIM', 'FUEL OIL INLET TEMP MGE4  [C]': 'MG4TE101/Meas1/PRIM', 'AUX CENTRAL FW COOLER TEMP  [C]': 'LC004.01/Meas1/PRIM', 'FUEL FLOW MGE2  [l/h]': 'MG2514/Meas1/PRIM', 'MGE4 EXHAUST GAS TEMP TC A INLET  [C]': 'MG4TE511/Meas1/PRIM', 'MG3_CWPreheat.03': 'MG3_CWPreheat/OutRunning/PRIM', 'SHAFT THRUST STBD  [kN]': 'SP053/Meas1/PRIM', 'MGE1 HT WATER TEMP JACKET A OUTLET  [C]': 'MG1TE402/Meas1/PRIM', 'MG2 FREQ  [hz]': 'PM110.06/Meas1/PRIM', 'DRAFT FWD [m]': 'RG009C/Meas1/PRIM', 'MGE JACKET COOLING FW PORT   TEMP  [C]': 'CF103.01/Meas1/PRIM', 'FUEL FLOW MGE3  [l/h]': 'MG3514/Meas1/PRIM', 'MGE3 FUEL OIL TEMP [C]': 'OE035/Meas1/PRIM', 'BOILER2 WATER CIRC PUMP1 RUN [-]': 'SM005/OutRunning/PRIM', 'GC_S1_shv_SAT': 'GC_S1_shv_SAT/Meas1/PRIM', 'MAIN BEARING NO 3 TEMP MGE1 [C]': 'MG1TE703/Meas1/PRIM', 'POSITIONLATITUDE [min]': 'IBS009/Meas1/PRIM', 'MGE3 FUEL OIL BOOSTER PUMP PRESS [bar]': 'OE010/Meas1/PRIM', 'Relative Density  [mol%]': 'GC_S1_rd/Meas1/PRIM', 'MAIN CSW PUMP1 RUN [-]': 'SW002/OutRunning/PRIM', 'MAIN BEARING NO0 TEMP MGE3 [C]': 'MG3TE700/Meas1/PRIM'}
    return dictionary[name]

def tagno2name(tagno):
    """
    name2tagno(name) converts a variable tag number to a name.
    
    Input:
        - name: Variable tag number
        
    Output:
        - tagno: Variable name
    """
    dictionary = {'MG2TE201/Meas1/PRIM': 'MGE2 LO TEMP ENGINE INLET  [C]', 'MG4TE517/Meas1/PRIM': 'MGE4 EXHAUST GAS TEMP TC A OUTLET  [C]', 'MG2PT401/Meas1/PRIM': 'MGE2 HT WATER PRESS JACKET INLET  [bar]', 'MG2TE272/Meas1/PRIM': 'MGE2 LO TEMP TC OUTLET  [C]', 'MG4TE705/Meas1/PRIM': 'MAIN BEARING NO5 TEMP MGE4 [C]', 'SP058/Meas1/PRIM': 'SHAFT SPEED PORT  [rpm]', 'EG005/Meas1/PRIM': 'EGE 2 EXHAUST GAS OUTLET MGE3 TEMP  [C]', 'SM012/OutRunning/PRIM': 'BOILER FEED WATER PUMP1 RUN [-]', 'SW010/Meas1/PRIM': 'SW TEMP TEMP [C]', 'IBS009/Meas1/PRIM': 'POSITIONLATITUDE [min]', 'MG1PT201/Meas1/PRIM': 'MGE1 LO PRESS ENGINE INLET  [bar]', 'MG4TE101/Meas1/PRIM': 'FUEL OIL INLET TEMP MGE4  [C]', 'SW006/OutRunning/PRIM': 'MAIN CSW PUMP3 RUN [-]', 'LD002.01/Meas1/PRIM': 'LD COMPRESSSOR1 CURRENT (HIGH SPEED) A [A]', 'MP1091/Meas1/PRIM': 'PM1 POWER ACTUAL [kW]', 'LD154/Meas1/PRIM': 'LD COMPRESSSOR2 DIS TEMP C [C]', 'PM130.05/Meas1/PRIM': 'MG4 VOLT [V]', 'EG011/Meas1/PRIM': 'EGE 1 WATER DRUM PRESS  [bar]', 'GC_S1_COMP_nC6/Meas1/PRIM': 'N Hexane  [mol%]', 'PM100.05/Meas1/PRIM': 'MG1 VOLT [V]', 'PM005.05/Meas1/PRIM': 'FEEDER HM1LM1 POWER  [kW]', 'MG2TE600/Meas1/PRIM': 'MG2_Air temp TC inlet  [C]', 'SW001/Meas1/PRIM': 'MAIN CSW PUMP1 PRESS  [bar]', 'GH030.01/Meas1/PRIM': 'VAPOUR TO GCU FLOW [kg/h]', 'SW031./OutRunning/PRIM': 'SW031..03', 'PM031.05/Meas1/PRIM': 'FEEDER HC1LC1 POWER  [kW]', 'PM002.05/Meas1/PRIM': 'BUSTIE HM1HC1 POWER  [kW]', 'MG019/Meas1/PRIM': 'MGE1 ENGINE SPEED [rpm]', 'GH001/Meas1/PRIM': 'VAPOUR HEADER FWD TEMP [C]', 'GC151/OutRunning/PRIM': 'GC151.03', 'MG2TE402/Meas1/PRIM': 'MGE2 HT WATER TEMP JACKET OUTLET  [C]', 'LD054/Meas1/PRIM': 'LD COMPRESSSOR1 DIS TEMP C [C]', 'MG4TE402/Meas1/PRIM': 'MGE4 HT WATER TEMP JACKET A OUTLET  [C]', 'GC013/Meas1/PRIM': 'GCU COMBUSTION AIR FLOW  [kg/h]', 'GH026.02/Meas1/PRIM': 'ATMOSPHERIC TEMP [C]', 'CP032/Stop/PRIM': 'CARGO TANK3 FG PUMP STOP [-]', 'GC016/Meas1/PRIM': 'GCU DILUTION AIR  FLOW LOW [mbar]', 'SW032./OutRunning/PRIM': 'SW032..03', 'IBS003/Meas1/PRIM': 'WIND SPEED  [kts]', 'MG4513/Meas1/PRIM': 'FUEL OIL HEATER OUTLET TEMP MGE4  [C]', 'CT033/Meas1/PRIM': 'CARGO LEVEL - TANK4  [m]', 'SP054/Meas1/PRIM': 'SHAFT SPEED STBD  [rpm]', 'OE010/Meas1/PRIM': 'MGE3 FUEL OIL BOOSTER PUMP PRESS [bar]', 'MG4TE600/Meas1/PRIM': 'MG4_Air temp TC inlet  [C]', 'FV022/Meas1/PRIM': 'DRAIN POT LVL [mm]', 'MG1513/Meas1/PRIM': 'FUEL OIL HEATER OUTLET TEMP MGE1 [C]', 'PM120.06/Meas1/PRIM': 'MG3 FREQ  [hz]', 'MG4PT201/Meas1/PRIM': 'MGE4 LO PRESS ENGINE INLET  [bar]', 'MG1SE528/Meas1/PRIM': 'MG1 TC B SPEED  [rpm]', 'CT030/Meas1/PRIM': 'CARGO LEVEL - TANK1  [m]', 'MG1TE521/Meas1/PRIM': 'MGE1 EXHAUST GAS TEMP TC B INLET  [C]', 'SP103/Meas1/PRIM': 'FUEL OIL DENSITY AT 15.6C  [kg/l]', 'OE035/Meas1/PRIM': 'MGE3 FUEL OIL TEMP [C]', 'CP033/Stop/PRIM': 'CARGO TANK4 FG PUMP STOP [-]', 'EG010/Meas1/PRIM': 'EGE 2 EXHAUST GAS OUTLET MGE4 PRESS  [mmH2O]', 'IBS005/Meas1/PRIM': 'Water depth  [m]', 'MG1TE272/Meas1/PRIM': 'MGE1 LO TEMP TC OUTLET A  [C]', 'MG3TE511/Meas1/PRIM': 'MGE3 EXHAUST GAS TEMP TC  INLET  [C]', 'SW002/OutRunning/PRIM': 'MAIN CSW PUMP1 RUN [-]', 'GH074/Meas1/PRIM': 'FG TO MGE4 TEMP [C]', 'MG1TE706/Meas1/PRIM': 'MAIN BEARING NO 6 TEMP MGE1 [C]', 'EG008/Meas1/PRIM': 'EGE 1 EXHAUST GAS OUTLET MGE2 PRESS  [mmH2O]', 'IBS002/Meas1/PRIM': 'SPEED THROUGH WATER  [kts]', 'PM029.05/Meas1/PRIM': 'BUSTIE HC1HC2 POWER  [kW]', 'GC_S1_COMP_CO2/Meas1/PRIM': 'Carbon Dioxide  [mol%]', 'SW004/OutRunning/PRIM': 'MAIN CSW PUMP2 RUN [-]', 'MGE-TOT.01/Meas1/PRIM': 'FUEL GAS FLOW TO MGE  [kg/h]', 'GC_S1_COMP_iC4/Meas1/PRIM': 'GC_S1_COMP_iC4', 'LC003/OutRunning/PRIM': 'AUX COOL FW PUMP2 RUN [-]', 'MG1TE403/Meas1/PRIM': 'MGE1 HT WATER TEMP JACKET B OUTLET  [C]', 'SP101/Meas1/PRIM': 'MDO DENSITY AT 15.6C  [kg/l]', 'MG1TE511/Meas1/PRIM': 'MGE1 EXHAUST GAS TEMP TC A INLET  [C]', 'GC175/OutRunning/PRIM': 'GC175.03', 'OE007/Meas1/PRIM': 'MGE2 FUEL OIL BOOSTER PUMP PRESS [bar]', 'MG3TE432/Meas1/PRIM': 'MGE3 HT WATER TEMP HT CAC OUTLET  [C]', 'MG4514/Meas1/PRIM': 'FUEL FLOW MGE4  [l/h]', 'PM110.06/Meas1/PRIM': 'MG2 FREQ  [hz]', 'MG4PT901/ProMeas/PRIM': 'MGE4 MAIN FUEL GAS PRESS [bar]', 'GC127/OutRunning/PRIM': 'GC127.03', 'MG1512/Meas1/PRIM': 'FUEL VISCOSITY MGE1  [cst]', 'GH020/Meas1/PRIM': 'VAPOUR HEADER ABS PRESS [mbar A]', 'MG1TE700/Meas1/PRIM': 'MAIN BEARING NO 0 TEMP MGE1 [C]', 'CA004/Meas1/PRIM': 'MAIN AIR RESERVOIR COM LINE PRESS  [bar]', 'PM110.08/Meas1/PRIM': 'MG2 CURRENT [A]', 'MG1TE401/Meas1/PRIM': 'MGE1 HT WATER TEMP JACKET INLET  [C]', 'GC030/Meas1/PRIM': 'GCU OIL BURNER SECONDARY AIR FAN PRESS [mbar]', 'MG3PT101/Meas1/PRIM': 'FUEL OIL INLET PRESS MGE3  [bar]', 'MG3TE707/Meas1/PRIM': 'MAIN BEARING NO7 TEMP MGE3 [C]', 'MG3TE272/Meas1/PRIM': 'MGE3 LO TEMP TC OUTLET  [C]', 'MG3513/Meas1/PRIM': 'FUEL OIL HEATER OUTLET TEMP MGE3  [C]', 'PM100.06/Meas1/PRIM': 'MG1 FREQ  [hz]', 'OE034/Meas1/PRIM': 'MGE2 FUEL OIL TEMP [C]', 'PM018.05/Meas1/PRIM': 'FEEDER HM2FD2 POWER  [kW]', 'GC_S1_InfWobb/Meas1/PRIM': 'Inferior Wobbe Index  [mol%]', 'MG2513/Meas1/PRIM': 'FUEL OIL HEATER OUTLET TEMP MGE2  [C]', 'MG3TE600/Meas1/PRIM': 'MG3_Air temp TC inlet  [C]', 'IBS001/Meas1/PRIM': 'SPEED OVER GROUND  [kts]', 'EG007/Meas1/PRIM': 'EGE 1 EXHAUST GAS OUTLET MGE1 PRESS  [mmH2O]', 'GC167/OutRunning/PRIM': 'GC167.03', 'MG4TE703/Meas1/PRIM': 'MAIN BEARING NO3 TEMP MGE4 [C]', 'MG4PT401/Meas1/PRIM': 'MGE4 HT WATER PRESS JACKET INLET  [bar]', 'IBS016/Meas1/PRIM': 'RUDDER ANGLE STBD [deg]', 'MG2TE705/Meas1/PRIM': 'MAIN BEARING NO5 TEMP MGE2 [C]', 'RG021/Meas1/PRIM': 'LIST  [deg]', 'MG1TE527/Meas1/PRIM': 'MGE1 EXHAUST GAS TEMP TC B OUTLET  [C]', 'MG119/Meas1/PRIM': 'MGE2 ENGINE SPEED [rpm]', 'SP051/Meas1/PRIM': 'SHAFT POWER STBD  [kW]', 'MP1090/Meas1/PRIM': 'PM1 SPEED [rpm]', 'MG1PT601/Meas1/PRIM': 'MGE1 CHARGE AIR PRESS AT ENGINE INLET  [bar]', 'RD017/Meas1/PRIM': 'REDUC GEAR STBD LO INLET TEMP [C]', 'GH071.01/Meas1/PRIM': 'FG TO MGE3 FLOW [kg/h]', 'SW011/Meas1/PRIM': 'AUX CSW PUMP1 PRESS  [bar]', 'LC004/OutPosition/PRIM': 'AUX CENTRAL FW COOLER TEMP  [C]', 'SW016/OutRunning/PRIM': 'AUX CSW PUMP3 RUN [-]', 'PM110.05/Meas1/PRIM': 'MG2 VOLT [V]', 'SM005/OutRunning/PRIM': 'BOILER2 WATER CIRC PUMP1 RUN [-]', 'MG1514/Meas1/PRIM': 'FUEL OIL MGE1 FLOW [l/h]', 'MG2TE700/Meas1/PRIM': 'MAIN BEARING NO0 TEMP MGE2 [C]', 'MG2512/Meas1/PRIM': 'FUEL VISCOSITY MGE2  [cst]', 'SP106/Meas1/PRIM': 'NITROGEN CONTENT  [mol%]', 'RG012C/Meas1/PRIM': 'DRAFT AFT [m]', 'GC_S1_COMP_nC4/Meas1/PRIM': 'N Butane  [mol%]', 'MG1SE518/Meas1/PRIM': 'MG1 TC A SPEED  [rpm]', 'GC143/OutRunning/PRIM': 'GC143.03', 'MG2TE401/Meas1/PRIM': 'MGE2 HT WATER TEMP JACKET INLET  [C]', 'MG2TE432/Meas1/PRIM': 'MGE2 HT WATER TEMP HT CAC OUTLET  [C]', 'PM001.05/Meas1/PRIM': 'BUSTIE HM1HM2 POWER  [kW]', 'OE013/Meas1/PRIM': 'MGE4 FUEL OIL BOOSTER PUMP PRESS [bar]', 'MG3TE201/Meas1/PRIM': 'MGE3 LO TEMP ENGINE INLET  [C]', 'MG2TE702/Meas1/PRIM': 'MAIN BEARING NO2 TEMP MGE2 [C]', 'GC_S1_COMP_C3/Meas1/PRIM': 'Propane From Analyser  [mol%]', 'PM130.08/Meas1/PRIM': 'MG4 CURRENT [A]', 'CH4/Out/PRIM': 'Methane From Manual Input  [mol%]', 'CA005/OutRunning/PRIM': 'MAIN AIR COMPRESSSOR1 RUN [-]', 'MG1TE702/Meas1/PRIM': 'MAIN BEARING NO 2 TEMP MGE1 [C]', 'MG4TE511/Meas1/PRIM': 'MGE4 EXHAUST GAS TEMP TC A INLET  [C]', 'SM011/Meas1/PRIM': 'BOILER FEED WATER PUMP1 PRESS  [bar]', 'SP057/Meas1/PRIM': 'SHAFT THRUST PORT  [kN]', 'MG4TE432/Meas1/PRIM': 'MGE4 HT WATER TEMP HT CAC OUTLET  [C]', 'OE033/Meas1/PRIM': 'MGE1 FUEL OIL  TEMP [C]', 'MG4TE700/Meas1/PRIM': 'MAIN BEARING NO0 TEMP MGE4 [C]', 'GH070/Meas1/PRIM': 'FG TO MGE3 TEMP [C]', 'MG1TE705/Meas1/PRIM': 'MAIN BEARING NO 5 TEMP MGE1 [C]', 'GC_S1_COMP_C2/Meas1/PRIM': 'Ethane From Analyser  [mol%]', 'SW015/Meas1/PRIM': 'AUX CSW PUMP3 PRESS  [bar]', 'GC191/OutRunning/PRIM': 'GC191.03', 'SP104/Meas1/PRIM': 'FUEL OIL SULFUR CONTENT  [%]', 'SM013/Meas1/PRIM': 'BOILER FEED WATER PUMP2 PRESS  [bar]', 'PM038.05/Meas1/PRIM': 'FEEDER HC2LC2 POWER  [kW]', 'MG3TE517/Meas1/PRIM': 'MGE3 EXHAUST GAS TEMP TC  OUTLET  [C]', 'GC135/OutRunning/PRIM': 'GC135.03', 'MG3TE700/Meas1/PRIM': 'MAIN BEARING NO0 TEMP MGE3 [C]', 'SM003/OutRunning/PRIM': 'BOILER1 WATER CIRC PUMP2 RUN [-]', 'GC032/Meas1/PRIM': 'GCU EXHAUST GAS  TEMP [C]', 'SP056/Meas1/PRIM': 'SHAFT TORQUE STBD  [kNm]', 'IBS011/Meas1/PRIM': 'POSITIONLONGITUDE [min]', 'EG009/Meas1/PRIM': 'EGE 2 EXHAUST GAS OUTLET MGE3 PRESS  [mmH2O]', 'GC_S1_GPM/Meas1/PRIM': 'GPM  [mol%]', 'IBS004/Meas1/PRIM': 'WIND REL DIRECTION  [deg]', 'MG1PT101/Meas1/PRIM': 'FUEL OIL INLET PRESS MGE1 [bar]', 'PM130.06/Meas1/PRIM': 'MG4 FREQ  [hz]', 'EG012/Meas1/PRIM': 'EGE 2 WATER DRUM PRESS  [bar]', 'BL009.06/Meas1/PRIM': 'STBY BALLAST PUMP CURRENT [A]', 'MG4SE518/Meas1/PRIM': 'MGE4 TC A SPEED  [rpm]', 'LC009/Meas1/PRIM': 'PORT PROPULSION TRAFO INLET TEMP [C]', 'LD156/Meas1/PRIM': 'LD COMPRESSSOR2 DIS PRESS bar [bar]', 'GH026.01/Meas1/PRIM': 'ATMOSPHERIC PRESS [mbar A]', 'PM019.05/Meas1/PRIM': 'FEEDER HM2LM2 POWER  [kW]', 'MG2TE706/Meas1/PRIM': 'MAIN BEARING NO6 TEMP MGE2 [C]', 'PM100.07/Meas1/PRIM': 'MG1 POWER  [kW]', 'MG4512/Meas1/PRIM': 'FUEL VISCOSITY MGE4  [cst]', 'MG4TE201/Meas1/PRIM': 'MGE4 LO TEMP ENGINE INLET  [C]', 'C3H8/Out/PRIM': 'Propane From Manual Input  [mol%]', 'MG3_CWPreheat/OutRunning/PRIM': 'MG3_CWPreheat.03', 'LD056/Meas1/PRIM': 'LD COMPRESSSOR1 DIS PRESS bar [bar]', 'MG3TE702/Meas1/PRIM': 'MAIN BEARING NO2 TEMP MGE3 [C]', 'SW005/Meas1/PRIM': 'MAIN CSW PUMP3 PRESS  [bar]', 'MG1TE432/Meas1/PRIM': 'MGE1 HT WATER TEMP HT CAC OUTLET  [C]', 'GC014/Meas1/PRIM': 'GCU COMBUSTION AIR  TEMP [C]', 'MG2PT601/Meas1/PRIM': 'MGE2 CHARGE AIR PRESSURE AT ENGINE INLET  [bar]', 'LC008/Meas1/PRIM': 'STBD PROPULSION TRAFO INLET TEMP [C]', 'GMS_DFEPress/Meas1/PRIM': 'GMS_DFEPress', 'MG1TE600/Meas1/PRIM': 'MGE1 AIR TEMP TC INLET  [C]', 'CF003.01/Meas1/PRIM': 'MGE JACKET COOLING FW STBD   TEMP  [C]', 'SM002/OutRunning/PRIM': 'BOILER1 WATER CIRC PUMP1 RUN [-]', 'GC_S1_NeoPen/Meas1/PRIM': 'NeoPentane  [mol%]', 'RG011C/Meas1/PRIM': 'DRAFT MID STBD [m]', 'BL005.06/Meas1/PRIM': 'BALLAST PUMP2 CURRENT [A]', 'MG4PT101/Meas1/PRIM': 'FUEL OIL INLET PRESS MGE4  [bar]', 'MG1PT401/Meas1/PRIM': 'MGE1 HT WATER JACKET INLET PRESS [bar]', 'MP2090/Meas1/PRIM': 'PM2 SPEED [rpm]', 'GC_S1_COMP_iC5/Meas1/PRIM': 'I Pentane  [mol%]', 'GH062/Meas1/PRIM': 'FG TO MGE1 TEMP [C]', 'MG219/Meas1/PRIM': 'MGE3 ENG SPEED [rpm]', 'MG2PT201/Meas1/PRIM': 'MGE2 LO PRESS ENGINE INLET  [bar]', 'SP053/Meas1/PRIM': 'SHAFT THRUST STBD  [kN]', 'IBS008/Meas1/PRIM': 'POSITION LATITUDE [deg]', 'MG3SE518/Meas1/PRIM': 'MG3 TC A SPEED  [rpm]', 'MP2091/Meas1/PRIM': 'PM2 POWER ACTUAL [kW]', 'MG319/Meas1/PRIM': 'MGE4 ENG SPEED [rpm]', 'SW014/OutRunning/PRIM': 'AUX CSW PUMP2 RUN [-]', 'GC_S1_rd/Meas1/PRIM': 'Relative Density  [mol%]', 'LC004.01/Meas1/PRIM': 'AUX CENTRAL FW COOLER TEMP  [C]', 'RG009C/Meas1/PRIM': 'DRAFT FWD [m]', 'LC006/Meas1/PRIM': 'PM1 COOL FW OUTLETL TEMP  [C]', 'MG3514/Meas1/PRIM': 'FUEL FLOW MGE3  [l/h]', 'EG001/Meas1/PRIM': 'BOILER1 EXHAUST GAS TEMP  [C]', 'GH081/Meas1/PRIM': 'VAPOUR TO GCU PRESS [bar]', 'MG4TE272/Meas1/PRIM': 'MGE4 LO TEMP TC OUTLET A  [C]', 'GH063.01/Meas1/PRIM': 'FG TO MGE1 FLOW [kg/h]', 'MG1TE704/Meas1/PRIM': 'MAIN BEARING NO 4 TEMP MGE1 [C]', 'MG2TE511/Meas1/PRIM': 'MGE 2 EXHAUST GAS TEMP TC  INLET  [C]', 'MG2SE518/Meas1/PRIM': 'MG2 TC A SPEED  [rpm]', 'GH067.01/Meas1/PRIM': 'FG TO MGE2 FLOW [kg/h]', 'MG2TE704/Meas1/PRIM': 'MAIN BEARING NO4 TEMP MGE2 [C]', 'GC_S1_IdealBTU/Meas1/PRIM': 'Ideal BTU  [mol%]', 'GC034/Meas1/PRIM': 'GCU COMBUSTION AIR  FLOW LL TRIP [mbar]', 'RD018/Meas1/PRIM': 'REDUC GEAR STBD LO  PRESS [bar]', 'GC_S1_COMP_nC5/Meas1/PRIM': 'N Pentane  [mol%]', 'GC183/OutRunning/PRIM': 'GC183.03', 'LD102.01/Meas1/PRIM': 'LD COMPRESSSOR2 CURRENT (HIGH SPEED) A [A]', 'GH002/Meas1/PRIM': 'VAPOUR HEADER AFT TEMP [C]', 'EG002/Meas1/PRIM': 'BOILER2 EXHAUST GAS TEMP  [C]', 'CT031/Meas1/PRIM': 'CARGO LEVEL - TANK2  [m]', 'MG2TE517/Meas1/PRIM': 'MGE 2 EXHAUST GAS TEMP TC  OUTLET  [C]', 'EG006/Meas1/PRIM': 'EGE 2 EXHAUST GAS OUTLET MGE4 TEMP  [C]', 'CF002.01/Meas1/PRIM': 'MAIN CENTRAL FW COOLER STBD OUTLET  TEMP  [C]', 'GC_S1_shv_SAT/Meas1/PRIM': 'GC_S1_shv_SAT', 'SM007/Meas1/PRIM': '7K STEAM SERV MAIN LINE PRESS [bar]', 'PM120.07/Meas1/PRIM': 'MG3 POWER  [kW]', 'LC001/Meas1/PRIM': 'AUX COOL FW PUMP PRESS [bar]', 'GH066/Meas1/PRIM': 'FG TO MGE2 TEMP [C]', 'BL001.06/Meas1/PRIM': 'BALLAST PUMP1 CURRENT [A]', 'GC_S1_COMPR/Meas1/PRIM': 'COMPRESSSORressibility Factor  [mol%]', 'SM004/Meas1/PRIM': 'BOILER2 WATER CIRC PUMP PRESS [bar]', 'PM130.07/Meas1/PRIM': 'MG4 POWER  [kW]', 'EG004/Meas1/PRIM': 'EGE 1 EXHAUST GAS OUTLET MGE2 TEMP  [C]', 'MG4TE706/Meas1/PRIM': 'MAIN BEARING NO6 TEMP MGE4 [C]', 'SM014/OutRunning/PRIM': 'BOILER FEED WATER PUMP2 RUN [-]', 'MG2TE703/Meas1/PRIM': 'MAIN BEARING NO3 TEMP MGE2 [C]', 'IBS010/Meas1/PRIM': 'POSITION LONGITUDE [deg]', 'C2H6/Out/PRIM': 'Ethane From Manual Input  [mol%]', 'GC159/OutRunning/PRIM': 'GC159.03', 'PM008.05/Meas1/PRIM': 'FEEDER HM1FD1 POWER  [kW]', 'MG2514/Meas1/PRIM': 'FUEL FLOW MGE2  [l/h]', 'MG2TE701/Meas1/PRIM': 'MAIN BEARING NO1 TEMP MGE2 [C]', 'GH075.01/Meas1/PRIM': 'FG TO MGE4 FLOW [kg/h]', 'MG4TE701/Meas1/PRIM': 'MAIN BEARING NO1 TEMP MGE4 [C]', 'SP052/Meas1/PRIM': 'SHAFT TORQUE PORT  [kNm]', 'MI204/Meas1/PRIM': 'B/THR MTR POWER [kW]', 'MG1TE703/Meas1/PRIM': 'MAIN BEARING NO 3 TEMP MGE1 [C]', 'MG3PT901/ProMeas/PRIM': 'MG3PT901', 'MG1TE517/Meas1/PRIM': 'MGE1 EXHAUST GAS TEMP TC A OUTLET  [C]', 'SW012/OutRunning/PRIM': 'AUX CSW PUMP1 RUN [-]', 'MG2PT101/Meas1/PRIM': 'FUEL OIL INLET PRESS MGE2  [bar]', 'MG4TE704/Meas1/PRIM': 'MAIN BEARING NO4 TEMP MGE4 [C]', 'CP032/Start/PRIM': 'CARGO TANK3 FG PUMP START [-]', 'GC033/Meas1/PRIM': 'GCU EXHAUST GAS  TEMP HH TRIP [C]', 'GC_S1_shv/Meas1/PRIM': 'GC_S1_shv', 'FV026.01/Meas1/PRIM': 'MIST SEPARATOR OUTLET TEMP [C]', 'MG4TE702/Meas1/PRIM': 'MAIN BEARING NO2 TEMP MGE4 [C]', 'CF102.01/Meas1/PRIM': 'MAIN CENTRAL FW COOLER PORT OUTLET  TEMP  [C]', 'GH019/Meas1/PRIM': 'VAPOUR HEADER PRESS H [mbar]', 'MG4TE282/Meas1/PRIM': 'MGE4 LO TEMP TC OUTLET B  [C]', 'MG4SE528/Meas1/PRIM': 'MGE4 TC B SPEED  [rpm]', 'MG2_CWPreheat/OutRunning/PRIM': 'MG2_CWPreheat.03', 'MG3PT201/Meas1/PRIM': 'MGE3 LO PRESS ENGINE INLET  [bar]', 'OE004/Meas1/PRIM': 'MGE1 FUEL OIL BOOSTER PUMP PRESS [bar]', 'MG1TE201/Meas1/PRIM': 'MGE1 LO TEMP ENGINE INLET  [C]', 'MG3TE701/Meas1/PRIM': 'MAIN BEARING NO1 TEMP MGE3 [C]', 'Gas_LHV/B4/PRIM': 'GAS LHV Lower Heating Value  [MJ/kg]', 'MG3PT601/Meas1/PRIM': 'MGE3 CHARGE AIR PRESS AT ENGINE INLET  [bar]', 'MP1068/Meas1/PRIM': 'PM1 Propulsion Drive FW Inlet temp [C]', 'CP034/Meas1/PRIM': 'CARGO FUEL GAS PUMP PRESS [bar]', 'MG2TE601/Meas1/PRIM': 'MGE2 CHARGE AIR TEMP AT ENGINE INLET  [C]', 'MG3TE402/Meas1/PRIM': 'MGE3 HT WATER TEMP JACKET OUTLET  [C]', 'MG3PT401/Meas1/PRIM': 'MGE3 HT WATER PRESS JACKET INLET  [bar]', 'MG4TE527/Meas1/PRIM': 'MGE4 EXHAUST GAS TEMP TC B OUTLET  [C]', 'MG1PT901/ProMeas/PRIM': 'MG1PT901', 'PM100.08/Meas1/PRIM': 'MG1 CURRENT [A]', 'MG3512/Meas1/PRIM': 'FUEL VISCOSITY MGE3  [cst]', 'MG1TE701/Meas1/PRIM': 'MAIN BEARING NO 1 TEMP MGE1 [C]', 'MG2PT901/ProMeas/PRIM': 'MG2PT901', 'MG4TE601/Meas1/PRIM': 'MGE4 CHARGE AIR TEMP AT ENGINE INLET  [C]', 'SM006/OutRunning/PRIM': 'BOILER2 WATER CIRC PUMP2 RUN [-]', 'MG3TE703/Meas1/PRIM': 'MAIN BEARING NO3 TEMP MGE3 [C]', 'PM120.08/Meas1/PRIM': 'MG3 CURRENT [A]', 'MG2TE101/Meas1/PRIM': 'FUEL OIL INLET TEMP MGE2  [C]', 'PM110.07/Meas1/PRIM': 'MG2 POWER  [kW]', 'CF103.01/Meas1/PRIM': 'MGE JACKET COOLING FW PORT   TEMP  [C]', 'MG3TE704/Meas1/PRIM': 'MAIN BEARING NO4 TEMP MGE3 [C]', 'SW013/Meas1/PRIM': 'AUX CSW PUMP2 PRESS  [bar]', 'GC_S1_SUM/Meas1/PRIM': 'Unnormalised Sum  [mol%]', 'MG1TE707/Meas1/PRIM': 'MAIN BEARING NO 7 TEMP MGE1 [C]', 'SP100/Meas1/PRIM': 'MDO LOWER CALORIFIC VALUE  [kJ/kg]', 'IBS006/Meas1/PRIM': 'RUDDER ANGLE PORT [deg]', 'GC_S1_swi/Meas1/PRIM': 'GC_S1_swi', 'MG3TE706/Meas1/PRIM': 'MAIN BEARING NO6 TEMP MGE3 [C]', 'CA006/OutRunning/PRIM': 'MAIN AIR COMPRESSSOR2 RUN [-]', 'SW003/Meas1/PRIM': 'MAIN CSW PUMP2 PRESS  [bar]', 'PM120.05/Meas1/PRIM': 'MG3 VOLT [V]', 'GC_S1_DenNor/Meas1/PRIM': 'Normal Density  [mol%]', 'SM001/Meas1/PRIM': 'BOILER1 WATER CIRC PUMP PRESS [bar]', 'N2/Out/PRIM': 'Nitrogen From Manual Input  [mol%]', 'MG4PT601/Meas1/PRIM': 'MGE4 CHARGE AIR PRESS AT ENGINE INLET  [bar]', 'MG2TE707/Meas1/PRIM': 'MAIN BEARING NO7 TEMP MGE2 [C]', 'BH028/Meas1/PRIM': 'AFT COOL FW OUTLET TEMP [C]', 'MG1TE601/Meas1/PRIM': 'MGE1 CHARGE AIR TEMP AT ENGINE INLET  [C]', 'AB161/OutMeas/PRIM': 'AUX BOILER FUEL OIL FLOW [l/h]', 'MG1TE101/Meas1/PRIM': 'FUEL OIL INLET TEMP MGE1 [C]', 'RD118/Meas1/PRIM': 'REDUC GEAR PORT LO  PRESS [bar]', 'EG003/Meas1/PRIM': 'EGE 1 EXHAUST GAS OUTLET MGE1 TEMP  [C]', 'CP033/Start/PRIM': 'CARGO TANK4 FG PUMP START [-]', 'MG4TE403/Meas1/PRIM': 'MGE4 HT WATER TEMP JACKET B OUTLET  [C]', 'CT032/Meas1/PRIM': 'CARGO LEVEL - TANK3  [m]', 'OE036/Meas1/PRIM': 'MGE4 FUEL OIL TEMP [C]', 'PM016.05/Meas1/PRIM': 'BUSTIE HM2HC2 POWER  [kW]', 'MG3TE705/Meas1/PRIM': 'MAIN BEARING NO5 TEMP MGE3 [C]', 'LC007/Meas1/PRIM': 'PM2 COOL FW OUTLETL TEMP  [C]', 'MG4TE521/Meas1/PRIM': 'MGE4 EXHAUST GAS TEMP TC B INLET  [C]', 'RG010C/Meas1/PRIM': 'DRAFT MID PORT [m]', 'SP055/Meas1/PRIM': 'SHAFT POWER PORT  [kW]', 'MG4TE401/Meas1/PRIM': 'MGE4 HT WATER TEMP JACKET INLET  [C]', 'IBS007/Meas1/PRIM': 'HEADING  [deg]', 'RD117/Meas1/PRIM': 'REDUC GEAR PORT LO INLET TEMP [C]', 'MG3TE601/Meas1/PRIM': 'MGE3 CHARGE AIR TEMP AT ENGINE INLET  [C]', 'MG1TE282/Meas1/PRIM': 'MGE1 LO TEMP TC OUTLET B  [C]', 'SP102/Meas1/PRIM': 'FUEL OIL LOWER CALORIFIC VALUE  [kJ/kg]', 'SP105/Meas1/PRIM': 'GAS LOWER CALORIFIC VALUE  [kJ/kg]', 'MG4TE707/Meas1/PRIM': 'MAIN BEARING NO7 TEMP MGE4 [C]', 'MI210/Meas1/PRIM': 'B/THR CURRENT [A]', 'GC_S1_COMP_C1/Meas1/PRIM': 'Methane From Analyser  [mol%]', 'RG020/Meas1/PRIM': 'TRIM  [m]', 'MP2068/Meas1/PRIM': 'PM2 Propulsion Drive FW Inlet temp [C]', 'MG1TE402/Meas1/PRIM': 'MGE1 HT WATER TEMP JACKET A OUTLET  [C]', 'MG3TE401/Meas1/PRIM': 'MGE3 HT WATER TEMP JACKET INLET  [C]', 'MG3TE101/Meas1/PRIM': 'FUEL OIL INLET TEMP MGE3  [C]', 'GC_S1_COMP_N2/Meas1/PRIM': 'Nitrogen From Analyser  [mol%]'}
    return dictionary[tagno]           

def getVarNames(col):
    """
    getVarNames(col) uses the column of a DataFrame and an additional list of
    information to determine the variable tag number, name, system and unit.
    
    Input:
        - col: Column of a DataFrame
        
    Output:
        - (tagno, name, system, unit): Variable tag number, name, system and unit.
    """
    tag = col.name.split('/',2)
    if len(tag)>1:
        tag = tag[0]+tag_map[tag[1]]
    elif tag[0] == 'nan':
        tag = np.nan
    tagno = tag
    name = tag
    unit = '-'
    try:
        name = sl.loc[tag, 'RDS Name']
        system = sl.loc[tag, 'RDS Location']
        unit = sl.loc[tag, 'Unit']
    except KeyError:
        system = 'N/A'
    return (tagno, name, system, unit)


def getFrequencies(timestamps):
    """
    getFrequencies(timestamps) calculates a list of frequencies, one for each
    step between two timesteps.
    
    Input:
        - timestamps: List of n timestamps
        
    Output:
        - freq: List of n-1 frequencies
    """
    n = len(timestamps)
    if n < 2:
        return []
    else:
        dT = np.subtract(timestamps[1:n], timestamps[0:n-1])
        freq = 1 / (dT.seconds + dT.microseconds*(1e-06))
        return freq
    
def concatStructs(structs):
    """
    concatStructs(structs) takes a list of structs and concatenates them to one
    larger struct.
    
    Input:
        - structs: List of structs
        
    Output:
        - out: A struct containing all structs concatenated
    """
    n = len(structs) 
    if n < 2:
        return structs[0]
    out = structs[0]
    for idx in np.arange(n-1):
        struct = structs[idx+1]
        for key in struct.variables.keys():
            out.variables[key].values = np.append(out.variables[key].values, struct.variables[key].values)
            if len(out.variables[key].timestamps) == 0:
                out.variables[key].timestamps = np.append(out.variables[key].timestamps, struct.variables[key].timestamps)
                out.variables[key].timestamps = pd.DatetimeIndex(out.variables[key].timestamps)
            else:
                out.variables[key].timestamps = out.variables[key].timestamps.append(struct.variables[key].timestamps)
            out.variables[key].frequencies = np.append(out.variables[key].frequencies, struct.variables[key].frequencies)
    return out
    

def roundTimestamps(struct):
    """
    roundTimestamps(struct) takes a struct and rounds all the timestamps to the
    nearest seconds (without removing duplicate timestamps).
    
    Input:
        - struct: A data struct to process
        
    Output:
        - struct: Same struct with timestamps rounded
    """
    keys = struct.variables.keys()
    for key in keys:
        struct.variables[key].timestamps = pd.DatetimeIndex([(x + datetime.timedelta(microseconds=5e5)).replace(microsecond=0) for x in struct.variables[key].timestamps])
    return struct


def avgDuplicates(struct):
    """
    avgDuplicates(struct) takes a struct and checks for duplicate timestamps.
    If duplicates are found, they are removed and the corresponding values are
    replaced by the average of the values.
    
    Input:
        - struct: A data struct to process
        
    Output:
        - struct: Same struct with duplicate timestamps removed
    """
    for key in struct.variables.keys():
        d = {}
        for a, b in zip(struct.variables[key].timestamps, struct.variables[key].values):
            d.setdefault(a, []).append(b)
        tss = []
        vals = []
        for ts in d:
            tss.append(ts)
            vals.append(sum(d[ts])/len(d[ts]))
        struct.variables[key].values = np.array([val for (ts,val) in sorted(zip(tss,vals))])
        struct.variables[key].timestamps = pd.DatetimeIndex(tss).sort_values()
    return struct


def toTable(struct, case=1):
    """
    toTable(struct, case) takes a struct and converts it to a DataFrame.
    
    Input:
        - struct: A data struct to convert.
        - case: 1 - DataFrame with timestamps as indices filled with values
                    for each variable will be created.
                2 - DataFrame with integer indices filled with frequencies for
                    each variable will be created.
    
    Output:
        - df: DataFrame
    """
    dfs = []
    if case==1: # Creating table filled with values and timestamp indexing
        for k in struct.variables.keys():
            dfs.append(pd.DataFrame(data={k:struct.variables[k].values}, index=struct.variables[k].timestamps))
    if case==2: # Creating table filled with frequencies and integer indexing
        for k in struct.variables.keys():
            dfs.append(pd.DataFrame(data={k:struct.variables[k].frequencies}))
    return pd.concat(dfs,axis=1)
